#!/usr/bin/bash

MAX_JOBS=3

echo "Job Number "$$

for dir in ??????_*/; do

	RUNNING=$(ps -u gillis | grep s2a | wc -l)
	while [[ $MAX_JOBS -le $RUNNING ]]; do
		sleep 10s
		RUNNING=$(ps -u gillis | grep s2a | wc -l)
	done 	

	for f in $dir/*z0?.nemo; do
		echo processing $f
		s2a $f $f".dat" &
	done

done
